openapi: 3.0.0
info:
  title: SwanPipe API
  description: API for the SwanPipe Backend
  version: 1.0.0
paths:
  /login:
    post:
      summary: Returns a list of users.
      operationId: login
      security: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - loginId
                - password
              properties:
                loginId:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                required:
                  - token
                properties:
                  token:
                    type: string
  /login-account:
    get:
      summary: Gets information on the login account.
      operationId: loginAccount
      responses:
        200:
          description: JSON object with login account information
          content:
            application/json:
              schema:
                type: object
                required:
                  - loginId
                  - created
                properties:
                  loginId:
                    type: string
                  created:
                    type: string
                    description: Human readable date and time of creation

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      in: header

security:
  - BearerAuth
